export interface Language {
  code: string;
  label: string;
  flag?: string;
}

export const LANGUAGES: Language[] = [
  { code: 'af',     label: 'Afrikaans',               flag: '🇿🇦' },
  { code: 'ar',     label: 'Arabic',                  flag: '🇸🇦' },
  { code: 'bg',     label: 'Bulgarian',               flag: '🇧🇬' },
  { code: 'bn',     label: 'Bengali',                 flag: '🇧🇩' },
  { code: 'ca',     label: 'Catalan',                 flag: '🏳️' },
  { code: 'cs',     label: 'Czech',                   flag: '🇨🇿' },
  { code: 'da',     label: 'Danish',                  flag: '🇩🇰' },
  { code: 'de',     label: 'German',                  flag: '🇩🇪' },
  { code: 'el',     label: 'Greek',                   flag: '🇬🇷' },
  { code: 'en-AU',  label: 'English (Australia)',     flag: '🇦🇺' },
  { code: 'en-GB',  label: 'English (UK)',            flag: '🇬🇧' },
  { code: 'en-IN',  label: 'English (India)',         flag: '🇮🇳' },
  { code: 'en-NZ',  label: 'English (New Zealand)',   flag: '🇳🇿' },
  { code: 'en-US',  label: 'English (US)',            flag: '🇺🇸' },
  { code: 'es',     label: 'Spanish',                 flag: '🇪🇸' },
  { code: 'es-419', label: 'Spanish (Latin America)', flag: '🌎' },
  { code: 'et',     label: 'Estonian',                flag: '🇪🇪' },
  { code: 'fi',     label: 'Finnish',                 flag: '🇫🇮' },
  { code: 'fil',    label: 'Filipino',                flag: '🇵🇭' },
  { code: 'fr',     label: 'French',                  flag: '🇫🇷' },
  { code: 'fr-CA',  label: 'French (Canada)',         flag: '🇨🇦' },
  { code: 'gu',     label: 'Gujarati',                flag: '🇮🇳' },
  { code: 'he',     label: 'Hebrew',                  flag: '🇮🇱' },
  { code: 'hi',     label: 'Hindi',                   flag: '🇮🇳' },
  { code: 'hr',     label: 'Croatian',                flag: '🇭🇷' },
  { code: 'hu',     label: 'Hungarian',               flag: '🇭🇺' },
  { code: 'id',     label: 'Indonesian',              flag: '🇮🇩' },
  { code: 'it',     label: 'Italian',                 flag: '🇮🇹' },
  { code: 'ja',     label: 'Japanese',                flag: '🇯🇵' },
  { code: 'ko',     label: 'Korean',                  flag: '🇰🇷' },
  { code: 'lt',     label: 'Lithuanian',              flag: '🇱🇹' },
  { code: 'lv',     label: 'Latvian',                 flag: '🇱🇻' },
  { code: 'mr',     label: 'Marathi',                 flag: '🇮🇳' },
  { code: 'ms',     label: 'Malay',                   flag: '🇲🇾' },
  { code: 'nl',     label: 'Dutch',                   flag: '🇳🇱' },
  { code: 'no',     label: 'Norwegian',               flag: '🇳🇴' },
  { code: 'pa',     label: 'Punjabi',                 flag: '🇮🇳' },
  { code: 'pl',     label: 'Polish',                  flag: '🇵🇱' },
  { code: 'pt',     label: 'Portuguese',              flag: '🇵🇹' },
  { code: 'pt-BR',  label: 'Portuguese (Brazil)',     flag: '🇧🇷' },
  { code: 'ro',     label: 'Romanian',                flag: '🇷🇴' },
  { code: 'ru',     label: 'Russian',                 flag: '🇷🇺' },
  { code: 'sk',     label: 'Slovak',                  flag: '🇸🇰' },
  { code: 'sl',     label: 'Slovenian',               flag: '🇸🇮' },
  { code: 'sr',     label: 'Serbian',                 flag: '🇷🇸' },
  { code: 'sv',     label: 'Swedish',                 flag: '🇸🇪' },
  { code: 'sw',     label: 'Swahili',                 flag: '🇰🇪' },
  { code: 'ta',     label: 'Tamil',                   flag: '🇮🇳' },
  { code: 'te',     label: 'Telugu',                  flag: '🇮🇳' },
  { code: 'th',     label: 'Thai',                    flag: '🇹🇭' },
  { code: 'tr',     label: 'Turkish',                 flag: '🇹🇷' },
  { code: 'uk',     label: 'Ukrainian',               flag: '🇺🇦' },
  { code: 'ur',     label: 'Urdu',                    flag: '🇵🇰' },
  { code: 'vi',     label: 'Vietnamese',              flag: '🇻🇳' },
  { code: 'zh-CN',  label: 'Chinese (Simplified)',    flag: '🇨🇳' },
  { code: 'zh-TW',  label: 'Chinese (Traditional)',   flag: '🇹🇼' },
];

export const DEFAULT_LANGUAGE = LANGUAGES.find(l => l.code === 'en-US')!;
